### PR TITLE
fixes #56 - Project URL for multiple words

### LINKED ISSUE #56: Fix Project URL for multiple words
**Describe the bug**
When the project name is added with spaces, then the project URL generated contains `%20` in between the URLs. 

**To Reproduce**
1. Go to `/project/add`.
2. Type a project name like `An awesome app`
3. Submit the project.

**Expected behavior**
The project URL generated should be something like `5-An-awesome-app`, rather it gets redirected to `5-An%20awesome%20app` and the API call is done for the same.

### PR DESCRIPTION
**Pull request by thesmallstar**
I have fixed this issue in my version. But when I updated my repo with the current version, something seems to be changed and now no longer the user is redirected to the project page, but instead to home. am I missing something?

### CODE REVIEW

File: src/app/add/project/project.component.ts [hunk 1]
```diff
@@ -50,7 +51,10 @@ export class AddProjectComponent implements OnInit {
           (data: any) => {
             const project_name =
               data.data.insert_project.returning['0'].id + '-' + data.data.insert_project.returning['0'].project_name;
-            this.router.navigate(['/project/' + project_name + '/view']);
+            var str = project_name;
+            str = str.replace(/\s+/g, '-').toLowerCase();
+
+            this.router.navigate(['/project/' + str + '/view']);
```
Comment (WickedBrat) [inline src/app/add/project/project.component.ts]: this url has been changed to `/view/project/<name>`

**Comment by thesmallstar** [comment]
@WickedBrat  please verify :)
